require("plugin-settings.nvim-tree")
require("plugin-settings.lualine")
require("plugin-settings.cokeline")
require("plugin-settings.nvim-treesitter")
require("plugin-settings.litee-lib")
require("plugin-settings.litee-symboltree")
require("plugin-settings.git-blame")
require("plugin-settings.gitsigns")
require("plugin-settings.indent-blankline")
require("plugin-settings.mini-map")
require("plugin-settings.numb")
-- require("plugin-settings.actionmenu")
-- require("plugin-settings.conmenu")
-- require("plugin-settings.popup-menu")
require("plugin-settings.nui")
require("plugin-settings.comment")
require("plugin-settings.dressing")
require("plugin-settings.nvim-cmp")
require("plugin-settings.editorconfig")
require("plugin-settings.noice")
require("plugin-settings.which-key")
