#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# blesh (must be after interactivity test)
# [[ $- == *i* ]] && source /usr/share/blesh/ble.sh --rcfile "$HOME/.blerc"

# default configuration
alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

# mimic zsh run-help (alt-h) ability
run-help() { help "$READLINE_LINE" 2>/dev/null || man "$READLINE_LINE"; }
bind -m vi-insert -x '"\eh": run-help'
bind -m emacs -x '"\eh": run-help'

# command-not-found (pkgfile)
source /usr/share/doc/pkgfile/command-not-found.bash

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# aliases
alias ls=lsd

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# login programs
wslfetch

# starship prompt
eval "$(starship init bash)"

# gpg fix for wsl
export GPG_TTY=$(tty)

# blesh - final attach with starship (must be at the end)
# [[ ${BLE_VERSION-} ]] && ble-attach
